### ISSUE TITLE
Flask error

### ISSUE THREAD

**Issue by testernoobkali** [BC-SECURITY/DEFCON27#4]
Hello,

I have googled this for a past 3 hours and i cannot get it to work, i know Flask has to be installed  which is it, i have no idea why it does not work.  I am using a Kali linux. I really want to get this to work i been watching the video you guys done on def con 27 and it was so cool! Thanks  in advance.

Linux kali 4.9.0-kali4-686 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) i686 GNU/Linux
root@kali:~/Desktop/empire/Empire/setup# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.2
Codename:	n/a

Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages (1.1.1)
root@kali:~/Desktop/empire/Empire/setup# 

oot@kali:~/Desktop/empire/Empire/setup# ./reset.sh 

 [>] Enter server negotiation password, enter for random generation: 

 [*] Database setup completed!

Traceback (most recent call last):
  File "./empire", line 6, in <module>
    from flask import Flask, request, jsonify, make_response, abort, url_for
ImportError: No module named 'flask'

**Comment by Hubbl3** [comment]
@testernoobkali this is the repository for the slides. We have Empire supported in a separate repository here: https://github.com/BC-SECURITY/Empire

If you open an issue there and follow the template there we will be better able to help you. 

My first shot at it though would be that if you haven't ran pip with the requirements.txt you should try that first. If you downloaded the dev branch from our repo you will instead need to use pip3 as it is running in python 3 by default

**Comment by Hubbl3** [comment]
The issue is related to Empire and not this repo
